### ISSUE TITLE
process stucked

### ISSUE THREAD

**Issue by WEIYanbin1999** [Arthur-Heng/NLGraph#1]
Hello!
![image](https://github.com/Arthur-Heng/NLGraph/assets/127707751/4bf268cc-b9c7-4df5-9856-6e64879045ba)
Do you know if this is normal? It has taken 5 minutes and still not moved on the bar. Thanks and I expect your response.

**Comment by WEIYanbin1999** [comment]
Now it is hours...

**Comment by Arthur-Heng** [comment]
If you are in an area restricted by openai (e.g. China), you should use a proxy.
