### ISSUE TITLE
Missing Experimental Results for Hard Difficulty in Topological Sort Task

### ISSUE THREAD

**Issue by shoyua** [Arthur-Heng/NLGraph#10]
In the topological sort task, there are three different difficulty levels: Easy, Medium, and Hard. However, the paper only provides experimental results for the Easy and Medium levels. Could you please provide the experimental results for the Hard difficulty level as well?

**Comment by Arthur-Heng** [comment]
We did not have results for the hard part since it exceeded the token limitation for the model at that time, but current models will certainly not have the same problem and you can try them out on the data.
