### ISSUE TITLE
Shortest_path task problems

### ISSUE THREAD

**Issue by Xinyan2904** [Arthur-Heng/NLGraph#4]
When running the shortest_path tasks, I observed two problems:
1. The model is unable to create route directly connecting neighbor nodes. Namely, if the questioned nodes are directly connected, the model will not take this route as the predicted answer. It will always find another longer route.
2. The predicted answers connected nodes with weight = 0. Namely, sometimes the predicted route follows a route that doesn't exist.
Is there an issue in model training, or is it because of some errors in my operation?
If it's because of model training, is it possible to clarify in the prompt that "nodes with edge weighing 0 should not be connected"?

**Comment by Arthur-Heng** [comment]
It is normal that the model makes different kinds of mistakes. You can try any prompt to solve the graph problems.
