### ISSUE TITLE
file details

### ISSUE THREAD

**Issue by shoyua** [Arthur-Heng/NLGraph#5]
Thank you for sharing these data. 

I have a few questions regarding the details:
1. Could you kindly clarify on what does the first line number represent in the 'graph*.txt' file?
```txt
5 1 2
2 3
2 3
3 2
4 3
4 1
```
2. As per my understanding, 'main.json' appears to be similar to 'train.json' and 'test.json' in the context of supervised fine-tuning setting?

**Comment by Arthur-Heng** [comment]
Q1: Generally, the first number means the number of nodes and the the second number means the number of edges. This example seems to belong to the connectivity task, which is slightly different from other data: here the third number means the number of queries for each type (i.e. connected and not connected). The number pairs following the edges are the queries.

Q2: Main splits are split into train splits and test splits.
